### ISSUE TITLE
Added check before adding provided resources

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#112]
Before a resource is added as a provided relation, it should be checked, that the resource is not provided by another resource _group_.

This should prevent that a resource accidentally provided by multiple resources and that an AppServers/Apps consuming the resources can't be generated anymore. Error in such a case:
```
/pages/generationTest.xhtml @17,79 listener="#{generationTestController.init}": javax.ejb.EJBException: java.lang.RuntimeException: ResourceEntity [id=254252, name=appMeta] is provided by multiple other resources:AbstractResourceRelationEntity
```

**Comment by RetGal** [comment]
Added check for both, JSF and REST, implemented in pr #139

**Comment by yvespp** [comment]
With #139 the performance of the `Add Related Resource` decreased drastically:
* Production on 1.13.0:  1.5 s to open
* Test env with this change: 19 s to open

Measured with the dev tools of Chrome. The test DB is slower, but not by that much...
I think this is caused by the additional queries of the call here: https://github.com/liimaorg/liima/pull/139/files#diff-e55913b6be9d6a1eb6c2918a4e5f96fbR58
It has to fetch all relations of the resources.

@RetGal can you change it so that check is not used in the popup and it always shows both links (Add as consumed Resource | Add as provided Resource)? The validation is then only run when the `Add as provided Resource` link is clicked. If it is already provided show a user friendly error message and don't close the popup.

**Comment by yvespp** [comment]
Closed by #169

**Comment by yvespp** [comment]
Some how the performance optimization did not work. The popup is still slow and after adding a provided resource the link `Add as provided Resource` is missing in the popup -> it seams that it still checks all resources in the popup.

**Comment by RetGal** [comment]
@yvespp Indeed, only the most costy "a Resource can only be provided by exactly one ResourceGroup" was removed. The check that assures that a Resource can only be added once to the *same* ResourceGroup and the permission check are still performed.
Shall this all only be done when clicking on the link?

**Comment by yvespp** [comment]
Yes, I would only check it if the link is clicked. Maybe check, what the performance impact of the check is, before changing it.
Provided resources are rarely used and so I don't think the performance impact is justifiable.
