### ISSUE TITLE
AMW_angular/#/deployment wrong default version

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#113]
The angular screen AMW_angular/#/deployment selects the version number of an older release, if the AppServer only exist in the old release.

Steps to Reproduce:
1. Create an AppServer in RL1
2. Create an App in RL1 and add it to the AppServer
3. Set the version of the App to RL1 on env global
4 Create an additional Release of the App: RL2. RL2 ist after RL1 chronologically.
5. Set the version of the App in RL2 to RL2 on env global
6. Create a new deployment, select the App and RL2 as release, select any env.

Result: in the version field of the application RL1 is shown instead of RL2.

**Comment by RetGal** [comment]
Same cause as #127
