### ISSUE TITLE
Access parent from resource template

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#12]
In a template defined on a resource or resource type the parent resource (the resource that consumes or provides this resource) should be accessible via hash `parent`.

- `parent` is set in the same way as `consumer` in resource relation templates. It points to the parent that is currently being generated.
- The `parent` hash should also be available in properties defined on consumed/provided resources and resource relations.

This enables us to get rid of resource type relationship templates, as they would have feature parity.

Usecase: to be able to clone a git repo with a specific version tag I read the version property of the App consuming the GIT resource.
I currently use a workaround for this: `${appServer.my_app.Version}`
`my_app` hast to be changed for each app.

**Comment by yvespp** [comment]
Alternatively the current app could be added to the model or the version could be added to the deployment hash.

**Comment by phil-pona** [comment]
we'll need the generator regression tests for this feature in a test set, similar to what we had earlier with the testing project. @yvespp could you please provide the following:

- Sample Configuration that covers most of the current features
   - Templates (ResrouceType, Resource, Relation)
   - include generated Templates
   - navigation in model
   - resource Relations (Type map, identifier)
   - Softlinks
   - AMW Functions (global and local)
   - properties in general (values, propertydescriptors)
   - property inheritance 
   - access to general properties (apps, as, node, runtime, deployment, context)
- expected output generated on the filesystem

There are two ways we can setup these tests:
- H2 Test Database with test set
- Liquibase Script which creates the testdata seperately

I'm going to integrate the tests as general testcases then, and implement the feature based on the test cases

**Comment by phil-pona** [comment]
@yvespp started implementation on branch https://github.com/liimaorg/liima/tree/feature_access_parent can you please check if this is what you had in mind?

Test Setup
```
as(name: appserver)->app(name: application)->git
```
The template on the resource app:
```
${parent.name} 
```
results in
```
 appserver
```
The template on the resource git:
```
${parent.name} 
${parent.parent.name}
${parent.git.name} // is possible as well, not sure if it makes much sense though
```
results in
```
application
appserver
git
```
It's basically possible to access the parent resource over `${parent}`

As we made the template model refactoring a few years ago, it's soon making sense to refactor the Generation Package model as well, this is still the "old" impl. and since the change was implemented quick and dirty due to the lack of regression tests, it's becoming a bit messy. We should consider a refactoring after the regressiontests are stable and ready.

**Comment by yvespp** [comment]
For test data we have already an issue: #11 

I tested the branch and parent works in templates on resources (via parent.name) and resource relations (via consumer.parent.name and provider.parent.name).
However in properties of a relation I can't access the parent. I tries parent.name, consumer.parent.name and provider.parent.name. I always get an error that the property is not found: 

```
The following has evaluated to null or missing: ==> parent
[in template "_propertyEvaluation_" at line 1, column 3]
---- Tip: If the failing expression is known to be legally refer to something
that's sometimes null or missing,
either specify a default value like myOptionalVar!myDefault, or use
<#if myOptionalVar??>when-present<#else>when-missing</#if>.
(These only cover the last step of the expression; to cover the whole expression,
use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)?? ----
---- FTL stack trace ("~" means nesting-related): - Failed at: ${parent.name}
[in template "_propertyEvaluation_" at line 1, column 1] ----
```

What I'm trying to do is to access the app.Version in a related resource property.

**Comment by yvespp** [comment]
`parent ` overlaps a bit with `consumer` of the relation templates. I think it has exactly the same functionality?
Difference is that `parent` works everywhere and not only on relations templates.

We could think about replacing `consumer` and `provider` with `parent` later. In relation properties `consumer` and `provider` doesn't exist already.

**Comment by phil-pona** [comment]
Parent is now accessible in properties as well, @yvespp please test again. 
so for example if a property `testProperty` is defined on the git resource and its content is `${parent.name}`
a template on the application with the following content
```
${git.testProperty}
```
will result in
```
application
```
I'm not yet sure about the consumer and parent thing. The relation templates are kind of a special case. I purpose to handle that in a separate issue or feature
