### ISSUE TITLE
AMW_angular/#/deployment/: redeploy sometimes doesn't set an environment

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#122]
Sometimes the environment is not set on AMW_angular/#/deployment/ when clicking the redeploy link on a single deployment.

I can reproduce it when I close chrome completely, reopen it, go to AMW_web/pages/deploy.xhtml and then click redeploy.

**Comment by RetGal** [comment]
Fixed in pr #201

**Comment by yvespp** [comment]
On master the env is still sometimes not set on redeploy.

**Comment by RetGal** [comment]
@yvespp AMW_web/pages/deploy.xhtml is replaced by AMW_angular/#/deployments in this release

**Comment by yvespp** [comment]
yes, sorry. I happens on the new angular screen too. I was able to sometimes reproduce this by going repeatedly to Resources Tab -> Deploy Tab-> redeploy.

**Comment by yvespp** [comment]
closed by #
