### ISSUE TITLE
Role Permissions 

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#124]
Role app_developer permissions after migration:
![image](https://user-images.githubusercontent.com/15231595/28119642-dc20d040-6715-11e7-894b-26cdf243095b.png)

Desired/corrections:
* RESOURCE UPDATE APPLICATION -> only on APPLICATION 
* TEMPLATE_RESOURCE ALL APPLICATION -> only on APPLICATION, all Action
* AMWFUNCTION ALL APPLICATION -> ok
* TEMPLATE_RESOURCETYPE -> no rights, delete

**Comment by yvespp** [comment]
Role server_admin permissions after migration:
![image](https://user-images.githubusercontent.com/15231595/28120895-aab93a84-6719-11e7-8ea6-79b855087ae3.png)
Desired/corrections:
* RESOURCE CREATE DEFAULT_ONLY -> Ok
* RESOURCE DELETE DEFAULT_ONLY -> Ok
* All the other new permissions are not needed because they are included.

Btw. does DEFAULT_ONLY also include Runtimes?

**Comment by yvespp** [comment]
Role shakedown_admin:
![image](https://user-images.githubusercontent.com/15231595/28121075-4313ba3e-671a-11e7-964e-4ec26afc117b.png)
Desired/corrections:
* SHAKEDOWNTEST ALL -> OK
* All the other new permissions are not needed because they are included.

**Comment by yvespp** [comment]
Role viewer permissions after migration:
![image](https://user-images.githubusercontent.com/15231595/28121190-9aae3274-671a-11e7-8863-e13381e9cc9f.png)

Corrections:
* RESOURCE READ APPLICATIONSERVER -> Remove, included in other rule
* RESOURCE READ APPLICATION-> Remove, included in other rule

**Comment by RetGal** [comment]
@yvespp currently DEFAULT_ONLY does not include Runtimes

**Comment by yvespp** [comment]
closed by #130

**Comment by yvespp** [comment]
@RetGal I have to following corrections for the roles after the permission merge was merged:
admin_developer:
* Remove: RESOURCE ALL
* Remove: RESOURCE UPDATE ANY

app_developer
* Remove: RESOURCE READ
* Change: RESOURCE_TEST_GENERATION_RESULT -> should be restricted to same environments as permissions of role developer_deployer

config_admin
* Remove DEPLOYMENT ALL ANY -> contained in deploy role
* Delete RESOURCE UPDATE NON_DEFAULT_ONLY

server_admin
* Remove RESOURCE UPDATE APPLICATIONSERVER ANY
* Remove RESOURCE ALL ANY
* Remove RESOURCE UPDATE DEFAULT_ONLY
* Remove RESOURCE UPDATE ANY

Permission table is not sorted.

I think we should fix this in the scripts before releasing.

**Comment by RetGal** [comment]
Fixed by  #134

**Comment by yvespp** [comment]
One last correction:
Add these permissions to config_admin:
* RESOURCE_TEST_GENERATION_RESULT		ALL				ANY	  
* RESOURCE_TEST_GENERATION		ALL				ANY
