### ISSUE TITLE
No add role button?

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#125]
#104 i still can't add roles. I don't see any button to do so:
![image](https://user-images.githubusercontent.com/15231595/28122928-ed307d5e-671f-11e7-91bc-75a702d7ac66.png)

I'm logged in as config admin, maybe I'm messing a permission?

**Comment by RetGal** [comment]
It's implemented the same way as for adding users: Simply type a role name which does not exist yet, as soon as you add a permission to it, the new role is created and the permission assigned.
