### ISSUE TITLE
Angular: Create new deployment shows wrong Apps

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#127]
The Create new deployment GUI has some problems with depending on the releases of the AppServer and Apps. It also seems that the logic behind the GUI is different from the logic of the deploy page, which cases different behavior.

**Cases:**
Higher release numbers are newer: RL-1 < RL-2 < RL-3 etc.

1.  AppServer1 in RL-1, App1 in RL-2:
    * On create deployment GUI select AppServer1 and RL-1.
Expected: no App is shown
Actual: App1 is shown and deployment can be created. deploy.xhtml shows the AppServer1 without an App

    * On create deployment GUI select AppServer1 in RL-2.
Expected: App1 is shown an can deployed
Actual: App1 is shown but deploying it causes an error:
GUI: Server error
Debugger: HTTP Status 500: {"message":"ValidationException","detail":"Applications missing in request: App1"}

2. AppServer1 in RL-1 and RL-3, App1 in RL-1, App2 in RL-2
    * On create deployment GUI select AppServer1 and RL-1.
Works as expected: GUI shows App1 and deployment is created with App1

    * On create deployment GUI select AppServer1 and RL-2.
Expected: App1 and App2 are shown. AppServer can be deployed
Actual: Only App1 is shown. Deploying it causes an error:
GUI: Server error
Debugger:  HTTP Status 500 {"message":"ValidationException","detail":"Applications missing in request: App2"}

    * On create deployment GUI select AppServer1 and RL-3.
Works as expected: GUI shows App1 and App2. Deployment is created with App1 and App2

**Comment by RetGal** [comment]
Fixed with #135
