### ISSUE TITLE
Date Filter Comparator wird resettet bein hinzufügen weiteter Filter

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#132]
Von einem Liima Benutzer: 

> Ich habe ein Problem mit dem Filter Deployment date.
> ![filter](https://user-images.githubusercontent.com/15231595/28657961-7548f13c-72a9-11e7-8a86-ae520ccc23c0.png)
> 
> Wenn ich zusätzlich weitere Filter setze, wird das grösser gleich automatisch durch kleiner als ersetzt.
> Das ist sehr mühsam den Filter immer wieder neu zu setzen.

**Comment by RetGal** [comment]
Fixed in pr #189
