### ISSUE TITLE
Permission RESOURCE_PROPERTY_DECRYPT doesn't show encrypted properties if it is limited to a Res. Type or Res. Group

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#143]
If the permission RESOURCE_PROPERTY_DECRYPT is limited to a specific Res. Type or Res. Group the field of an encrypted property is editable, but clicking and activating it shows an empty field instead of the decrypted password.
Tested with app ch_mobi_adam and password property on relation to adIntern.

Maybe RESOURCETYPE_PROPERTY_DECRYPT is also affected?

**Comment by RetGal** [comment]
Fixed both in pr #178
