### ISSUE TITLE
Permission RESOURCE UPDATE can create an edit templates

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#144]
If a user has the permission RESOURCE UPDATE he can create an edit templates but not delete them.

Create, edit and delete of templates should be attached to permission RESOURCE_TEMPLATE and the corresponding ACTION defined in the documentation: https://github.com/liimaorg/docs/blob/master/content/permissions.md. 

RESOURCE_AMWFUNCTION can also only be created/edited/delete with the action ALL.

Probably also effects the RESOURCETYPE and RESOURCETYPE_TEMPLATE permission.

**Comment by RetGal** [comment]
Fixed in pr #150

**Comment by yvespp** [comment]
With RESOURCE_TEMPLATE READ ANY I can't open the templates to view the contents, the button is missing. With read I should see the content but not able to modify it.

- With RESOURCE_AMWFUNCTION READ I can see the edit button and read functions templates -> OK
- With RESOURCE_AMWFUNCTION CREATE and READ I can't create new function because the button is missing.
- With RESOURCE_AMWFUNCTION UPDATE and READ I can see to button to create new functions (which should not be shown) but trying to save a new template gives an permission exception (which is correct).
- Without RESOURCE_AMWFUNCTION DELETE and READ I can see delete button (which should not be shown) but clicking it gives a permission exception (which is correct).

**Comment by RetGal** [comment]
Fixed in pr #158

**Comment by yvespp** [comment]
* With RESOURCE_TEMPLATE READ and UPDATE I can view templates but not edit and save them, the button in missing and everything is read only. Seams to be attached to CREATE instead.
* With RESOURCE_AMWFUNCTION READ and CREATE I can open the create new function dialog but all the fields are read only and the `Create new function` button is missing. As with RESOURCE_TEMPLATE CREATE I should be able to create functions with these permission but not edit existing ones.
* With RESOURCE_TEMPLATE READ and CREATE I can open the new template dialog and edit but when I hit  `Create template` I get an auth exception.
