### ISSUE TITLE
Sorting of permissions confusing

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#164]
Example:
![image](https://user-images.githubusercontent.com/15231595/29081685-791e3290-7c63-11e7-8beb-c58f201fcc48.png)

First comes RESOURCE then RESOURCE_TYPE* and then RESOURCE_* agian. Same happens in the permission drop down.

All RESOURCE* etc. should be sorted together. Maybe ignoring underscore would fix it?

**Comment by RetGal** [comment]
Optimized in pr #179
