### ISSUE TITLE
Rename a resource with "-" to "_" doesn't work

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#223]
Replacing the "-" in a resource name with a "_" doesn't work, e.g.:
Rename "test-app" to "test_app" gives this error:
```
Warning!
A resource with the name test_app already exists!
```
Renaming in the other direction works.

This has probably because SQL LIKE is used and "_" is a wildcard character in JPA: http://www.objectdb.com/java/jpa/query/jpql/string

**Comment by RetGal** [comment]
@yvespp I corrected the behaviour for both, resources and resource types. The renaming of resources/resource types is currently implemented differently: a resource could be renamed to ReSoUrCe while in case of resource types this would not be possible (case insensitive). Is this correct or shall both behave the same way? (which?)
