### ISSUE TITLE
Redeploy uses resourceId instead of resourcegroupId

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#224]
After merging #216  redeploy gives errors:
* GET /AMW_rest/resources/resources/resourceGroups/249708/releases/
   Status Code:404 Not Found
* GET /AMW_rest/resources/deployments/canDeploy/249708?contextId=6
   Status Code:400 Bad Request

249708 is a resourceID but the methods require a resourcegroupId. Probably something got mixed up in #216.

**Comment by RetGal** [comment]
Fixed in pr #225
