### ISSUE TITLE
Deployment filter: Latest deployment job for ... shows two deployments for one env

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#23]
If the deployment date of two deployments of the same app end env are exactly the same, the deployment filter "Latest deployment job for App Server and Env" show both deployments instead of one.

How to reproduce:
1. Create a deployment request for an AppServer with deployment date tomorrow at 12:00.
2. Create a second deployment request for the same AppServer with the same deployment date.
3. Select deployment filter "Latest deployment job for App Server and Env"

**Comment by yvespp** [comment]
Higher deployment id winns

**Comment by RetGal** [comment]
Fixed in pr #200

**Comment by RetGal** [comment]
Fixed in pr #200
