### ISSUE TITLE
AMW_angular/#/deployments: filters come back

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#245]
After a "Clear filter" and "Apply filter" go to a different page, if you come back to the deployment page, the filters are set again.
In this case, no filter should be set.

**Comment by yvespp** [comment]
#248 doesn't fix this some how, filter still come back. Also a user might not click "Clear filters" but instead remove filters via trashcan icon and then hit "Apply filter".

**Comment by polandy** [comment]
could not reproduce

**Comment by polandy** [comment]
problem: When all filters are deleted via trash icon and no filter is applied the previous filter is loaded
