### ISSUE TITLE
Erweiterte Berechtigungsstruktur

### ISSUE THREAD

**Issue by eloy83** [liimaorg/liima#25]
Auf den Ebenen "Global", "Domain", "Environment" und pro Application/ApplicationServer sollen Berechtigungen gesetzt werden können (mit Vererbung). Wenn keine Berechtigung gesetzt ist, besteht auch keine Einsicht in die Struktur/Konfiguration.

Folgende Unterscheidungen sollten möglich sein:
- Alle Berechtigungen (admin)
- Bearbeiten von Konfigurationen (bestehend)
- Anlegen neuer Konfigurationen
- Einsicht in vorhandene Konfigurationen (mit und ohne Passwort)

Die Berechtigungen sollten wenn möglich über ein Mapping zu Active Directory (LDAP) Gruppen gesetzt werden können.

**Comment by phil-pona** [comment]
@yvespp Kannst Du Dir dieses Feature kurz anschauen und sagen in wie fern Du Anforderungen ergänzen würdest?

**Comment by wemu** [comment]
Hallo

ich würde die Berechtigungen pro Application/ApplicationServer gerne ergänzen um Deploy-Rechte.

Use-Case ist das eine einzelne Applikation auf eine bestimmte Umgebung deployed werden darf (über die REST API mit einem technischen User eine bestimmte Applikation auf Produktion). Derzeit können nur Umgebungen frei gegeben werden.

**Comment by yvespp** [comment]
Ich würde die Anforderungen wie folgt ergänzen:
* Wie @wemu vorgeschlagen hat, die Berechtigungen für Deployments sollten auch pro Umgebung und AppServer vergeben werden können.
* Die Config Rechte auf den Ressourcen sollten nicht nur pro App und AppServer vergeben werden können, sondern für beliebige Ressourcen und Ressource Typen. -> Teilweise muss es Teams auch möglich sein, andere Ressourcen zu erfassen und zu bearbeiten z.B. eigene WebServices, User etc.
* Für die Rest Services müssen die Berechtigungen auch gelten. So können einfach Daten aus Fremdsystem geliefert werden.
* Anpassungen Berechtigungen sollte ohne Restart der Applikation möglich sein. Im Momentan werden die Rollen nur auf dem Server neu geladen, auf dem man im GUI eingeloggt ist und die Anpassung macht. Ich denke Anpassungen von Berechtigungen wird viel häufiger vorkommen und ein Restart wird dadurch unpraktisch.

Sonstiges:
* Wir sollten uns überlegen, die Berechtigungen stark zu reduzieren, so wie @eloy83 vorgeschlagen hat. Momentan haben wir 140 Berechtigungen die teilweise schon nur einzelne Ressourcen Betreffen (AS und App), was wir ja jetzt generalisieren und dadurch nicht mehr viel Sinn machen. Auch sind die Berechtigungen pro Ressourcen wohl momentan zu fein granular. Vorschlag:
  * Zum editieren der Konfiguration einer Ressource 4-5 Berechtigungen (CRUD) dafür pro Ressource und Env vergebbar.
  * Für Deployments 2-3 Berechtigungen dafür pro AS und env vergebbar.
  * Restliche Berechtigungen wie heute: Settings, Berechtigungen verwalten, Globale Templates etc.

Ich habe das Gefühl, pro Team das AMW verwendet eine LDAP Rolle zu machen, wäre in unserem (Mobi) Fall zu aufwändig. Momentan müssten Rollen zusätzlich auch im Web.xml jeweis ergänzt werden, was ehere umständlich ist. Ich denke es müssen beide Fälle abgedeckt werden: Rollenmapping von LDAP Rollen auf AMW Rollen und Rollenvergabe direkt im AMW.

Irgendwie so:
```
LDAP Role -> AMW Role -> Permissions -> Permission Scope (Env, Resource)
LDAP User -> AMW Role
```

**Comment by RetGal** [comment]
Habe mit der Erweiterung des Berechtigungsmodells begonnen. 
Branch: https://github.com/liimaorg/liima/tree/feature_new_permissions.

**Comment by yvespp** [comment]
Feedback neues Berechtigungssystem:
@RetGal: Könntest du die einzelnen Fragen schon mal beantworten, dann könnte ich mich dran machen, die Berechtigungen selber zu testen.

## Allgemein
1.1 Was bedeutet create, read, update, delete für Ressource und Deployments, was ist hinter welcher Action versteckt? Könntest du das bitte im Doc Projekt dokumentieren? Z.B. was ist hinter Delete Deployment definieren, Deployments können ja nicht wirklich gelöscht werden? In welcher Permission ist definiert, welche welche Passwörter sehen kann?
1.2 Wenn man eine neue Permission hinzu fügt, sieht man im Dropdown nicht ob es eine neue oder alte Permission ist. Könnte man die darstellerisch unterscheiden? Ich weis gar nicht welche jetzt neu sind...
1.3 Wieso sind da die alten Berechtigungen auch noch aufgeführt? Sind die auch noch aktiv? Was ist dort die Idee? Wie kann ich testen, dass die neue Berechtigungen ohne die alten funktionieren?
1.4 Wie kann ich neue Rollen erstellen? Finde nirgendwo einen Button auf dem GUI.
1.5 Kann man auch Rollen direkt Usern zuweisen? Bei uns wird es wohl sehr viele Rollen geben, die ich nicht alle im LDAP verwalten möchte. Wie kompliziert ist es, das zu erweitern?
1.6 Resource Type Categories: überschneidet sich das nicht mit Resource Type? Würde jetzt eher darauf verzichten. Ev. könnte man einen Shortcut bei den Ressource Typen hinzufügen, der alle Default Ressourcen addet.
1.7 Wäre cool, wenn man beim hinzufügen von neuen Permissions grade mehrere Resource Gruppen, Typen, Actions und Environments angeben könnte. In der Tabelle könnte man sie auch zusammengefasst anzeigen. Würde das Managen der Permissions einiges einfacher und übersichtlicher machen.

## Permissions
2.1 Die Permissions der Rolle server_admin schein sich zu überlappen? Hat CREATE/DELETE für APPLICATIONSERVER, APPLICATION und NODE, aber auch CREATE/DELETE für DEFAULT_ONLY. Ist doch das gleiche? Siehe auch 1.7

## Darstellung Roles Screen:
3.1 Der Font der Tabelle ist sehr klein.
3.2 Im Permission Panel gibt es auf der linken Seite viel ungenutzter Platz. Ich würde das Pannel ganz weg lassen, ist ja schon über das Menü links klar, wo man ist. Kann man auch beim Create Deployment Screen weglassen. Der Titel vom Panel müsste es wohl Roles heissen und nicht Permissions. 
![empty_space](https://user-images.githubusercontent.com/15231595/26967249-d2334888-4cfd-11e7-8426-14a12a50cec8.JPG)

3.3 "Add" umbenennen auf "Add permission"?
3.4 Wenn man das Fenster verkleiner, kommt "Favorites only" irgendwann kurz auf eine neue Zeile und überdeckt dann den Titel vom Screen , bevor alles dann in ein Menü umgewandelt wird. Der Test der Tabelle geht dann auch über das Permission und Assigned Pannel hinaus. ![notitel](https://user-images.githubusercontent.com/15231595/26967048-049aa2f4-4cfd-11e7-929b-e08d542182e0.JPG)
3.5 Wenn der Screen ganz klein ist, ist das Menü links gar nicht mehr sichtbar.
3.6 Das Menü links find ich zu gross auf meinem Bildschirm. Denke man sollte dort eine Max Size definieren.
3.7 Beim verkleinern vom Fenster wird das Menü links mit dem Screen immer kleiner, dann plötzlich wieder grösser, dann wieder kleiner.
