### ISSUE TITLE
Deployment Excel Export: remove newline at the end of Applications column

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#262]
A newline at the end of the fields of the application column cause excel to show no apps after resizing the column.

**Comment by RetGal** [comment]
@yvespp shall the newlines in the content of the fields "deploymentParameters" and "stateMessage" be removed as well?

**Comment by yvespp** [comment]
Only newlines at the end should be renoved, not all newlines. If other
columns are affected it can be removed there too.

Am 21.11.2017 11:54 schrieb "RetGal" <notifications@github.com>:

**Comment by yvespp** [comment]
Hmm, the is still a newline at the end...
![image](https://user-images.githubusercontent.com/15231595/33425122-0e8c2c02-d5be-11e7-9e82-2042865b2db6.png)
