### ISSUE TITLE
Move deployment csv generation to server

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#267]
Move the logic for generating the deployment csv to rest `GET /deployments/filter` endpoint. If the request header `accept` is set to `text/csv`.

For the `GET /hostNames` endpoint we already have this:
* [HostNamesRest.getHostNames()](https://github.com/liimaorg/liima/blob/master/AMW_rest/src/main/java/ch/mobi/itc/mobiliar/rest/resources/HostNamesRest.java#L106)
* [ServerTupleCSVBodyWriter.java](https://github.com/liimaorg/liima/blob/master/AMW_rest/src/main/java/ch/mobi/itc/mobiliar/rest/resources/ServerTupleCSVBodyWriter.java)
* [Registration in RESTApplication.java](https://github.com/liimaorg/liima/blob/master/AMW_rest/src/main/java/ch/mobi/itc/mobiliar/rest/RESTApplication.java)

Why?
* Less logic in front end
* Less code duplication
* Less rest calls needed to build the csv

**Comment by yvespp** [comment]
Will fix #344

**Comment by RetGal** [comment]
@yvespp I had to create an additional endpoint: `/deployments/filterCsvExport`

**Comment by RetGal** [comment]
Fixed in #370
