### ISSUE TITLE
Feedback #234 config overview

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#295]
Here my feedback for #234:
* I don't get a warning when I'm overwriting a property on a related resource. A warning only appears if the another property is already overridden in a sub env. A warning should appear if a property in a relation is set that overrides values defined on the resource itself.

**Comment by RetGal** [comment]
@yvespp Just to assure that I got you right: the warning on a property on a relation shall **only** appear, if it overrides a property defined on the (slave-) resource?

**Comment by yvespp** [comment]
@RetGal 
For overwrite on resources it's ok like how it is.
For relation properties:
* For properties on global or domain env: show a read warning if it overwrites values defined on the resource. Ideally the a confirm dialog should appear when the user hits save which displays what get's overwritten.
* The config overview button should be shown if properties defined on the relation or on the resource are overwritten.
* The config overview should show what values are overwrite on the relation and on the resource.
