### ISSUE TITLE
properties REST endpoint return successfully for non-existing resources

### ISSUE THREAD

**Issue by dsbrng25b** [liimaorg/liima#325]
The REST endpoint /resources/{resourceGroupName}/{releaseName}/relations/{relatedResourceGroupName}/{relatedReleaseName}/properties does return successfully (http 200) even if the resourceGroupName or the relatedResourceGroupName does not exist.
The same behaviour applies to the REST endpoint for a single resource /resources/{resourceGroupName}/{releaseName}/properties

In my opinion the endpoint should return with a HTTP 404 error if a resource does not exist.

**Comment by RetGal** [comment]
Fixed in #376
