### ISSUE TITLE
http 400 Bad Request - Node not active

### ISSUE THREAD

**Issue by andyzwa** [liimaorg/liima#352]
If a deployment is created over the rest interface and the appServers node is not "active" the http resonse is actually "http 400 Bad Request".

If a defined error will be returned, it would be more precise and the promoting of an environment will be easier.

**Comment by RetGal** [comment]
@andyzwa Currently it returns a http 400 state with the message "No active Node found on Environement X" in the response body. Which http state would you expect? 424 (Failed dependency)?

**Comment by andyzwa** [comment]
@RetGal Yes, the return code 424 makes more sense for me than 400. I didn't found something smarter.. 424 it's ok for me.

**Comment by yvespp** [comment]
Or 422 (Unprocessable Entity)

**Comment by yvespp** [comment]
424 seems to fit better:
https://stackoverflow.com/questions/27286857/can-i-use-http-response-424-when-a-request-requires-another-request-to-be-done-f

**Comment by RetGal** [comment]
Implemented in #374
