### ISSUE TITLE
Dash in YAML editor difficult to see

### ISSUE THREAD

**Issue by LaunchPairs** [liimaorg/liima#358]
In the inline YAML editor it is difficult to distinguish between a blank - which is show as a gray dot - and a dash. This often leads to errors that are hard to find.
![liima-yaml-dash](https://user-images.githubusercontent.com/39255467/39985088-9d863076-575d-11e8-81e8-e5b2dc98be6c.png)

**Comment by yvespp** [comment]
We should try make the dots lighter via css first to see if it's enough.

**Comment by RetGal** [comment]
Fixed in #369
