### ISSUE TITLE
REST: add 'Test Generation' endpoint 

### ISSUE THREAD

**Issue by lbeyeler** [liimaorg/liima#360]
Add GET AMW_Rest/analyze/testGeneration/{resourceGroupName}/{releaseName}/{env}

Runs the test generation for the selected resource and returns

- 200 when the test generation is successful
- 500 when the test generation fails, the response body should contain the error logs

Thanks, LB

**Comment by RetGal** [comment]
@lbeyeler Endpoint will be available unter `AMW_Rest/resources/analyze/testGeneration/{resourceGroupName}/{releaseName}/{env}` - as `resources` is the application path
