### ISSUE TITLE
editTemplateView.xhtml: "Compare with history" not updated after save on Wildfly 12.0

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#363]
Maybe related to #362

**Comment by RetGal** [comment]
@yvespp I can not reproduce the described behaviour using Wildfly 12.0.0 Final

**Comment by yvespp** [comment]
I can reproduce this by creating a new template:
1. Click `New Template` on a resource
2. Put some text in Template name, Path/filename and template, click "Create template"-> "Compare with history" shows only "Don't compare"
3. Edit templates again, click Save change -> "Compare with history" only shows one date instead of two.
4. After selecting a date "Compare with history" suddenly shows two dates.
