### ISSUE TITLE
Richface WildFly 14 incompatibilities

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#436]
With WildFly 14 different RichFaces/JSF issues poped up:
* `h:selectManyCheckbox` now returns List<Integer> instead of List<String>. Fixed see #435. Probably an actual bug in the Liima JSF code.
* In the head section of xhtml JSF pages the script `/AMW_web/org.richfaces.resources/javax.faces.resource/org.richfaces.staticResource/4.5.10.Final/PackedCompressed/packed/packed.js` is included multiple times.
* After a save on editResourceView.xhtml with property with a default value the "Changes detected" dialogue shows up when you click a context or try to leave the page.

I’m going to revert the Docker image back to WildFly 13 for the moment. 

Not sure if this is because WildFly 14 is still buggy or RichFaces is incompatible with the JSF Version used...

**Comment by yvespp** [comment]
We should try to add our own JSF implementation: <http://docs.wildfly.org/15/Admin_Guide.html#JSF>

**Comment by yvespp** [comment]
We should try again with WildFly 17

**Comment by RetGal** [comment]
Tested with WildFly 17 without any issues.

**Comment by lackrobin** [comment]
Should we update the Docker image to WildFly 17 then?

**Comment by lackrobin** [comment]
I also did not experience any of these bugs when running on WildFly 17

**Comment by yvespp** [comment]
@yvespp yes we should, WildFly 13 is quite old now...
