### ISSUE TITLE
Host in multiple Releases even if not the case

### ISSUE THREAD

**Issue by maweng80** [liimaorg/liima#472]
Since Runtimes have several Releases, when you search a Hostname that belongs only to 1 AppSrv/Release, Liima indicates "multiple" in the "AppServer Release" Column.

Moreover, the REST Call "hostNames" seems to have the same bug : 
If you execute the call by specifying a"host" (which is only configured once in Liima) and "disableMerge=true", liima send back 2 times the same data (ServerTuple) in the answer.

**Comment by RetGal** [comment]
[
![buggy](https://user-images.githubusercontent.com/19471064/64184876-736fb000-ce6c-11e9-98cc-e96d68283ae3.png)
](url)
