### ISSUE TITLE
editResourceView: UI doesn't update correctly after removing runtime

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#479]
![image](https://user-images.githubusercontent.com/15231595/57281039-6d2e1a80-70aa-11e9-94d6-bdfa82d317e2.png)

**Comment by mburri** [comment]
This issue is not specific for runtimes - it also pops up for the other resource types, as long itt is the last of its type.

**Comment by mburri** [comment]
Could we replace this view with angular?

**Comment by yvespp** [comment]
How would you do that, by replacing the whole screen?

**Comment by mburri** [comment]
@sdedijer and I thought about this possibility yes...

**Comment by yvespp** [comment]
It would be very nice to replace the screen but it's a lot of work...
Some REST services are still missing and the screen has quite a lot of features that have to be ported.
But if I you see a way to port it then I'm all for it!

**Comment by yvespp** [comment]
> This issue is not specific for runtimes - it also pops up for the other resource types, as long it is the last of its type.

I can only reproduce it with runtimes...

**Comment by mburri** [comment]
The runtime for the resource is stored in a map called runtimeRelations
https://github.com/liimaorg/liima/blob/69925f4457d760aa5111a9c7bf507b0dfbae9088/AMW_web/src/main/java/ch/puzzle/itc/mobiliar/presentation/resourceRelation/ResourceRelationModel.java#L87

This map is populated with the runtime relation on page load:
https://github.com/liimaorg/liima/blob/69925f4457d760aa5111a9c7bf507b0dfbae9088/AMW_web/src/main/java/ch/puzzle/itc/mobiliar/presentation/resourceRelation/ResourceRelationModel.java#L488

it looks like this map stays untouched if the runtime is removed - I'm checking now if it's ok to always reinitialize the map in setApplicationsAndRuntime without breaking something else.

When I investigated this issue, I noticed some more strange behaviour when relations are added or removed, not only for runtimes.

but I think a major refactoring of this view and its beans is necessary...
