### ISSUE TITLE
New release of relation uses old prop descriptor for copied instance property

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#487]
Most likely this is the underlying cause for #484.

How to reproduce:
1. Create new resource resA of type application
1. Create new resource resB of any type
1. In resB add an instance property. Take note of the descriptor id.
1. In resA add resB as a consumed relation
1. In relation form resA to resB set the value to `myUniqueValue123` in the new instance property
1. In the DB search for the new value: `select * from tamw_property where to_char(substr(value, 0, 30)) = 'myUniqueValue123';`
  The descriptor_id should be the same as above.
1. Create a new release of resB

=> search the DB again. It should have two values with two different deployment descriptor ids as the copy created a new resource with a new descriptor.
But what happens is that the two values have the same descriptor id, meaning the value is attached to the property descriptor of the old release instead of the new one.
This then causes the optimized oracle query to fetch wrong data which in turn causes an exception. The old query is immune to this.
If you set the a new property value in the relation from resA to resB it then gets attached to correct descriptor.

If I change the descriptor id of the new property to the descriptor id of the new release in the DB, then the optimized query works and also shows the copied value.

This bug seems to have been in Liima for a long time....

**Comment by yvespp** [comment]
After this is fixed we can switch back to the optimized query

**Comment by sdedijer** [comment]
Hi @yvespp ,

Sorry for asking it here as well, but I need your help again. Thanks for nice step-by-step description, but I got stuck already on the step number 3, I don't find **descriptor_id** once I _Add new instance Property_. I don't see this descriptor_id in GUI. Could you please help me how to find it?

Thanks a lot in advance!

**Comment by yvespp** [comment]
I think you can see the id in the url of the descriptor gui else you have to check in the db table.

**Comment by mburri** [comment]
The property descriptor id is not at all visible in the GUI - you have to get it from the database:
```
select * from TAMW_PROPERTYDESCRIPTOR t where PROPERTYNAME = 'new-property'

**Comment by yvespp** [comment]
The id is visible for me in the url under propDescId...:
![image](https://user-images.githubusercontent.com/15231595/104754930-14a59080-575a-11eb-8d43-f986cc1889ad.png)

**Comment by mburri** [comment]
finally tracked it down to: https://github.com/liimaorg/liima/blob/24c7b02ca41c6e86a24829bcb7e0dac37d97f7f1/AMW_business/src/main/java/ch/puzzle/itc/mobiliar/business/property/entity/PropertyEntity.java#L196

now investigating if `target.setDescriptor(getDescriptor().getCopy(new PropertyDescriptorEntity(), copyUnit));` fixes the issue...

**Comment by yvespp** [comment]
If the descriptor is part of the copied resource it should never reference the same descriptor.
If the descriptor is not part of the copied resource (when the descriptor is defined on the type) it should reference the same descriptor as before.

**Comment by mburri** [comment]
Ok - this means the simple solution above does not work - it would always create a new descriptor.
