### ISSUE TITLE
Frontend-Test-Setup is broken

### ISSUE THREAD

**Issue by RetGal** [liimaorg/liima#501]
Frontend-Test-Setup is broken
Might be caused by Karma upgrade 1.7.1 to 4.1.0

**Comment by mburri** [comment]
reverting to karma 1.7.1 (and other karma related dependecies) does not help.
Tests are failing with 
`$ is not defined`

looks as if the root cause was the jquery update...

**Comment by mburri** [comment]
it was not the update itself but the changes in order to restore the datepicker functionality 7bd1ee7

Works in the Browser since jQuery usually gets loaded on the application entry point - but when running the tests in isolation....
