### ISSUE TITLE
Liquibase scripts are broken

### ISSUE THREAD

**Issue by RetGal** [liimaorg/liima#502]
Liquibase scripts after 1.17.8 cause errors when run against local oracle-xe

**Comment by yvespp** [comment]
* Needs now Ora DB dump
* H2 db needs updating
* Current Oracle Express version doesn't support indexes

**Comment by yvespp** [comment]
H2 will be updated with #508 
Script should run with new Oracle Docker Image: https://hub.docker.com/_/oracle-database-enterprise-edition
