### ISSUE TITLE
Host set in predeploy not available in deploy

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#507]
Sometime the host set via Liima rest service in the predeploy phase is not available in the deployment run of the same deployment. In a subsequent deployment the host property is available and the deployment succeeds.
 
Relevant log entries:
```
# Starting deployment script on AMW server liima-6569ffff67-xhjsz
# Mode: PREDEPLOY
2019-09-02 16:12:45,779 INFO refact.amwVMBuilder Hostname of VM is: ld9t007a
2019-09-02 16:12:45,779 INFO refact.amwVMBuilder Setting hostname on relation from defa_wrapper KR-19.07 to node node_01 RL-14.10
2019-09-02 16:12:46,709 INFO refact.amwVMBuilder Update request 36676 finished, success = True
2019-09-02 16:12:45,779 INFO refact.amwVMBuilder Setting hostname on relation from defa_wrapper KR-19.07 to node node_01 RL-14.10
2019-09-02 16:13:35,072 INFO AmwDeployRunner Marking predeployment as success
# Starting deployment script on AMW server liima-6569ffff67-p7fr8
# Mode: DEPLOY
2019-09-02 16:13:43,776 INFO refact.amwConfiguration Config: 
2019-09-02 16:13:43,777 INFO refact.amwConfiguration     host: 
```

**Comment by yvespp** [comment]
This is very strange and can't really happen:
* PREDEPLOY runs asynchronous and the java transaction ends when the deploy scripts starts.
* setting the hostname happens via rest and run's in its own transaction.
* marking the deployment as success also happens via rest and runs in its own transaction. This also triggers the DEPLOY phase via event.
* The DEPLOY phase runs on a different Liima instance.

Unless we have some cache somewhere this should be impossible?!

**Comment by yvespp** [comment]
We should try to update to a newer Wildfly version and see if it fixes it

**Comment by sdedijer** [comment]
Hi @yvespp ,

Sorry that I don't know it, but could you please help me to reproduce this issue. Where is predeploy? Could you please describe step by step how to reproduce this issue? Sorry really once again for asking it.

And also once I know how to do it, do you think that we should also take the latest version of Wildfly and try to reproduce it with latest version as well?

Thanks a lot for your help in advance and BR.

**Comment by yvespp** [comment]
I can only reproduce this if there is more then one Liima server.
The reproduce you have to:
* Setup two Liima servers connecting to the same database
* Set a hostname via REST PUT /hostNames/{node}/{release}/{env}/{appServer} to one of the servers
* Immediately after the above call read the hostname from the other server via GET /hostNames

**Comment by yvespp** [comment]
Test calls:
```
# Test Calls
curl -X PUT "$LIIMA_HOST/AMW_rest/resources/resources/test_app1/test_rl/properties/Version?env=Global" -H "accept: application/json" -H "Content-Type: text/plain" -d "MyVersion3"
curl -X GET "$LIIMA_HOST/AMW_rest/resources/resources/test_app1/test_rl/properties/Version?env=Global" -H "accept: application/json"
```

**Comment by mburri** [comment]
I'm confused - first you wrote to set a host name via /hostNames resource, but your test calls use a different endpoint (/resources/resources/...) instead of /resource/hostNames

What is the correct endpoint to reproduce this issue?

**Comment by mburri** [comment]
Hmm - just tried once again - and the new host name is not set. It looks like It's only possible to set the hostname once - the first time a new entry is created with `"appServerRelease": "multiple",`

I think that I'm on the wrong path - @yvespp could you point me in the right direction please?

**Comment by mburri** [comment]
Another observation in this context while investigating issue #487 

Some (not all) of the values I provided as hostNames ended up in the TAMW_PROPERTY table:

305915,4,1151,version04
305914,0,1151,version1
305913,0,1151,version1
305912,0,1151,version1
305911,0,1151,version1
305910,0,1151,4th-try
305909,0,1151,4th-try
305908,0,1151,4th-try
305907,0,1151,4th-try
305906,0,1151,my-host-name-that-i-just-set
305905,0,1151,my-host-name-that-i-just-set
305904,0,1151,my-host-name-that-i-just-set
305903,0,1151,my-host-name-that-i-just-set

**Comment by yvespp** [comment]
I tested again and I can't reproduce this issue anymore... Also found no errors in our prod related to this issue.
I attached my tests scripts that I used, in case it shows up again
[test_via_rest.txt](https://github.com/liimaorg/liima/files/5830367/test_via_rest.txt)
[test_via_generate.txt](https://github.com/liimaorg/liima/files/5830380/test_via_generate.txt)
