### ISSUE TITLE
Replace eonasdan-bootstrap-datetimepicker 

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#510]
See #483
The datetimepicker is no longer maintained, see: https://github.com/Eonasdan/bootstrap-datetimepicker
Requires a separate version of jquery.

**Comment by sdedijer** [comment]
Hi Yves,

Regarding eonasdan datatimepicker. We have noticed that it still works also with latest angular changes on cli_migration branch. Do you think that we should keep it and maybe change it once it doesn't work properly or do you want us to change it now?

We checked if there is some nice datetimepicker that we can use instead and we found that with ng-bootstrap we can use date picker and time picker separately, which is possible to put together. Apart from ng-bootstrap, we might use some other datetimepicker as well, maybe we find also something similar like eonasdan.

Thanks a lot in advance for your answer and best regards,
Sanja

**Comment by yvespp** [comment]
I'm not sure if I tried to update it because of a security issue in a dependecy...
We can wait with this and check if there are still security issues after the angular cli migration.

**Comment by sdedijer** [comment]
Ok @yvespp , then we wait with this issue and check if it is ok after the angular cli migration. Thanks a lot!

**Comment by mburri** [comment]
@yvespp It seems that there are no open security issues related to the datepicker - we should replace it nonetheless because it is a jquery datepicker in its core. Thus the integration with angular is not straightforward (the angular way)

**Comment by yvespp** [comment]
Sound good to me!

**Comment by yvespp** [comment]
Maybe we can use something like this: https://github.com/ng-bootstrap/ng-bootstrap/issues/2086#issuecomment-423573672
Looks like a combination of the existing ng-bootstrap time and datepicker.

All the other datetimepickers I found are old and not maintained....
