### ISSUE TITLE
Falsche Version bei Redeploy von altem Release

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#52]
**Gegeben**
App und AppServer in RL-1. Noch keine weitern Releases existieren für die App und den AppServer.
RL-1 ist vor RL-2.

**Reproduzieren**
1. Deployment wird gemacht mit RL-2 mit Version 0.1 (Obwohl App in RL-2 noch nicht existiert).
2. RL-2 von der App wird erstellt und das Property Version auf 0.2 gesetzt
3. Redeployment von Deployment aus 1

**Resultat**
Es wird Version 0.2 genommen anstatt 0.1 wie im Ursprungs-Deployment.

Durch das Redeployment wurde die Ressource Id von RL-1 übernommen (sieht man in der DB unter TAMW_DEPLOYMENT -> APPLICATIONSWITHVERSION -> applicationId). Bei einem neuen Deployment mit RL-2 würde es die Ressource Id von RL-2 nehmen.
Das führt jetzt offenbar dazu, dass die Version vom Ursprungs-Deployment ignoriert wird und die Version von der App im  RL-2 genommen wird. Es schein als würde das Überschreiben der Version in dieser Situation nicht mehr funktionieren.

Vermutlich kommt es zu weitern Problemen, wenn die applicationId in der Zwischenzeit gelöscht wurde.

**Lösungsansätze**
1. Redeployment verwendet Audit Daten vom Urspungs-Deployment -> ist nicht was der User will, alle Änderungen würde so ignoriert.
2. Erkennen der Situation und dem User einen Fehler anzeigen.
3. applicationId und applicationName im neuen Deployment updaten wenn möglich, sonst Fehler anzeigen. Geht nicht wenn Releases verändert wurden und noch ein Rename der App stattgefunden hat.

Ich bin für 3.

**Comment by yvespp** [comment]
Ich hatte noch so einen Fall da wurde eine App umbenannt und dadurch wurde beim redeploy von einer alten Version die App nicht gefunden. Im Network Tool von Chrom hat man diese Meldung gesehen:

```
{"message":"ValidationException","detail":"Applications not found: ch_mobi_javabatch_fofa_verifier / Applications missing in request: ch_mobi_fofa_verifier_javabatch"}
```

Ich denke wir sollte Variante 2 wählen: die Zusammensetzung von Apps/Releases etc. aus dem Redeployment mit dem Vergleichen, was aktuell vorhanden ist.  Wenn es nicht match, entweder best effort die Daten übernehmen oder dem User einfach einen Fehler anzeigen.

**Comment by yvespp** [comment]
Wir sollten uns auch überlegen, wie wir Fehler aus der Rest Schnittstelle anzeigen sollen. Im Fall oben könnte man gut die Detail Message auf dem GUI anzeigen.

**Comment by RetGal** [comment]
@yvespp Das Problem betreffend der falschen Version beim Redepoyment ist höchstwahrscheinlich bereits mit #135 behoben worden. (es wird im Beispiel die korrekte Version 0.1 redeployed). Der Fall von umbenannten/gelöschten Applikationen wird nun bereits im Vorfeld mittels Fehlermeldung abgefangen und die Deployment-Buttons ausgeblendet. (pr #173)
