### ISSUE TITLE
Warning "A newer release for this resource exist. Are you..." doesn't disappear

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#520]
How to reproduce:
1. Create a ressource
1. Create a second release of the resource
1. In the older release add a related resource
1. The warning pops up: "A newer release.."
1. After clicking ok or cancel the dialog appears again immediately.

![image](https://user-images.githubusercontent.com/15231595/71342771-076da080-255e-11ea-8682-eb6ba8e107ba.png)

Related to #513 and started to appear with update to JBoss EAP 7.2.

**Comment by yvespp** [comment]
As a workaround you can keep holding the enter keep, which will confirm all dialogues.

**Comment by mburri** [comment]
This also happens with Wildfly 18 - the problem might be that the richfaces js library is included 14 times in the page when running on wildfly18 and EAP but only once when running on Wildfly 12.

I suspect that its the jsf implementation (2.3 for EAP 7.2 and Wildfly vs. 2.1 and 2.2. for Wildfly 12) that causes this behaviour.

**Comment by yvespp** [comment]
We could include our own JSF implementation, JBoss/Wildfly supports this: https://access.redhat.com/documentation/en-us/red_hat_jboss_enterprise_application_platform/7.3/html/configuration_guide/javaserver_faces_jsf_configuration

**Comment by yvespp** [comment]
Downgrading to jsf 2.2 fixes this, will send pull request.
