### ISSUE TITLE
Unit test failure

### ISSUE THREAD

**Issue by sleroy** [liimaorg/liima#529]
I am trying to build the project using : 

![image](https://user-images.githubusercontent.com/5766034/75438103-adbb9500-5957-11ea-9813-30ed5576043a.png)

Here is my issue : 

![image](https://user-images.githubusercontent.com/5766034/75438085-a4cac380-5957-11ea-93bc-898e5fd3e2fe.png)

Could you update the Software requirements if there is a difference between my environment and yours ?

**Comment by yvespp** [comment]
Hi @sleroy
Java 11 is not support yet. I documented the build preconditions in #534 and created #535 for JDK 11 support.
