### ISSUE TITLE
Rest: create resources

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#57]
Like on the GUI, it should be possible to crate new Apps, AppServer and other resource instances via rest:

Use cases;
* Create a resource instance (or new release of a resource)
* Create relations between resources 
* Invoke copy from on new AppServer and App

**Comment by yvespp** [comment]
Ref #51

**Comment by RetGal** [comment]
Implemented 
- Create a resource instance (or new release of a resource)
- Create relations between resources

**Comment by RetGal** [comment]
Implemented "copy from" in pull  #138
