### ISSUE TITLE
NullPointerException on editTemplateView.xhtml after remove of relation

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#704]
Setup: a resource with a template and a related resource
Reproduce:
1. Remove the related resource
2. Edit the template
3. Click "Save changes"
=> this will result in this error:
```
A general System Failure occurred!
/pages/editTemplateView.xhtml @70,41 rendered="#{editTemplateView.canModifyTemplates()}": javax.ejb.EJBException: java.lang.IllegalArgumentException: id to load is required for loading
```
or:
```
#{editTemplateView.save()}: javax.ejb.EJBException: java.lang.NullPointerException
```
Stacktrace:
```
Caused by: java.lang.NullPointerException
        at deployment.AMW.ear.AMW_business.jar//ch.puzzle.itc.mobiliar.business.template.boundary.TemplateEditor.saveTemplateForRelation(TemplateEditor.java:153)
```

**Comment by mburri** [comment]
@yvespp 
We found some additional bugs while analyzing this issue.

1. Removing a relation of a consumed resource that has no `RelationName` is not possible. Even though the notification that the relation was successfully removed is displayed to the user. If `RelationName` is set, the relation will be removed. Removing relations to consumed resources works fine.
2. Removing the last relation of a resource leads to an invalid state in the frontend, as shown in the following image: 
![image](https://github.com/liimaorg/liima/assets/4577216/891b3234-e4f8-43eb-a7e3-eb11d69128f2)

We think that the basic problem with the current issue (NullPointerException on editTemplateView.xhtml after removing the relation) is probably somehow related to the above mentioned bugs.

A workaround would be to force a page reload after removing a relation - but that might lead to new error messages.

I think it would be worthwhile to tackle problems (1) and (2) first, and then work on the original problem of this issue.

But there are some questions regarding a proper solution to (1). Must consumed resources always have a `RelationName`, and should this be enforced by the application? Or would it be ok to just inform the user that the relation could not be removed? Or should it just work with unnamed consumed resources?

Should we open separate issues for (1) and (2), or is it ok to treat them as part of this issue?

What's your opinion?

**Comment by yvespp** [comment]
1. Removing a relation without a relation name in our production (EAP 7.4) works correctly, but with ghcr.io/liimaorg/liima/liima:v1.17.31 (Wildfly 26.1.3) it doesn't work. Seems to be due to the different JBoss versions.
Also with the Wildfly version when I set a relation name of relation without a name and reload , I have two relations...
2. This happens in our production as well

I think the null pointer showed up after my changes in the last release 1.17.31 on this screen: https://github.com/liimaorg/liima/pull/701

If the relation name is not set (identifier in the db), the relation name is just the name of the resource. It should just work without the relation name.

I think it's better to open separate issues for 1 and 2, as 1 doesn't show up in our prod yet and 2 is more cosmetic.
