### ISSUE TITLE
Delegation of permissions

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#74]
To enable self service for applications, applicationServers and other resources, users should be able to create new resources and give permissions to other users to manage them:
* Users should be able to give permissions to other users on resources that they can manage themselves.
* Users should get managements rights to a resource automatically, if they created it.

Extends #69 for #57.

**Comment by RetGal** [comment]
@yvespp Which permissions shall users be able to delegate?
- RESOURCE (READ, UPDATE) (?)
- RESOURCE_AMWFUNCTION (?)
- RESOURCE_TEMPLATE (?)
- RESOURCE_PROPERTY_DECRYPT (?)

**Comment by yvespp** [comment]
They should be able to delegate all permissions they have themselves.
If they create an resource, the should get all permissions for that resource, meaning RESOURCE_* action ALL.
