### ISSUE TITLE
Make identifier of resource relations editable

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#78]
A user should be able to set the name of resource relation.
The identifier name should be shown as a property on the relation on the editResourceView, similar as the resource name is shown on a resource.

Example relations identifiers of batch:
![image](https://cloud.githubusercontent.com/assets/15231595/24707218/0a4c84fa-1a13-11e7-8bb7-300687e93695.png)

**Comment by RetGal** [comment]
Implemented

**Comment by yvespp** [comment]
Closed by #110
