### ISSUE TITLE
"There are unsaved changes" sometimes shows up without changes

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#80]
Sometime the dialog "There are unsaved changes" shows up, even though there are no changes.
![image](https://cloud.githubusercontent.com/assets/15231595/24756011/92b784b0-1adc-11e7-8540-5ec9201db07c.png)

It's not clear to me what you have to do to run into this bug. The same actions sometimes cause the dialog to show but not always...
The only reliable way I was able to reproduce this bug is by changing the env while the site is still loading. The easiest way to achieve this is to keep clicking on an env while the site is loading till the dialog shows up.
It seams to happen more frequently on apps that have a lot of properties and relations.

It startet to happen in the 1.12.2 release, in 1.12.1 it worked fine.
I tested with Chrome.

**Comment by phil-pona** [comment]
did you save the passord to login into the application with firefox or crhome? if so, it might be replaced to the properties with the name password and then the app thinks something changed

**Comment by yvespp** [comment]
We use the client certificate to login to Liima and don't use passwords.
Also it only happens sometimes.
