### ISSUE TITLE
provide docker image for liima

### ISSUE THREAD

**Issue by shoutcool** [liimaorg/liima#82]
Liima is a deployment tool, but the deployment description of liima itself includes several manual steps (isn't it ironic?;)
- installing java 8
- installing old jboss 6.4 version
- installing jdbc driver
- installing war
- configuring security
- configuring data source

You should instead provide a docker image. The users of liima should not care about these low level tasks. It's way to complicated, if someone just want to give liima a try, without spending hours.

**Comment by yvespp** [comment]
Totally agree, we also need this for testing.
Currently Liima isn't compatible with EAP 7 / Wildfly, see #9. This make it hard to provide a Docker Image as we probably can't redistribute EAP 6.4 and there isn't a Wildfly versions that is JEE 6 only...
