### ISSUE TITLE
Rest API for properties does not return values if a later release is passed

### ISSUE THREAD

**Issue by wemu** [liimaorg/liima#86]
Hello

The properties resource: GET /resources/{resourceGroupName}/{releaseName}/properties currently only returns values if a release is given that really exists, instead of also using the fallback to the latest existing one.

Example: my_server -> my_application, the application is on release "1704" (there are newer ones like 1710 but this application does not have that configured)

`GET /resources/my_application/1704/properties?env=W`

will return the properties. But

`GET /resources/my_application/1710/properties?env=W`

will return an empty array. Yet this is possible for deployments. I can successfully deploy this server/application for 1710 (it will fallback to the latest available configuration).

Could the Rest API please also respect this behavior? So a later release will return the properties of the one that would be used if there is no release yet for this application.

The Use-Case is to retrieve the deployments (witch gives the release), and from there retrieve the properties for this application.

**Comment by wemu** [comment]
It seems other endpoints behave like this as well:

`GET /resources/{resourceGroupName}/{releaseName}/relations`

with `GET /resources/my_application/1704/relations` will work but using `GET /resources/my_application/1710/relations` returns a 404 status code.

One could determine the available releases from `GET /resources/my_application` but there is no precise way of matching that to the releases used for deployments other than replicating the release configuration outside Liima (it seems there is no resource to determine releases and their order?)

**Comment by yvespp** [comment]
Suggestions: 
* add a flag fallback. If true, falls back to the closest release in the past.
* add an additional rest endpoint to get the closest release of a resource and a give release.

**Comment by RetGal** [comment]
Implemented additional endpoint:
`GET /resources/{resourceGroupName}/lte/{releaseName}`

**Comment by RetGal** [comment]
Important: BugFix is based on 1.13 release, because most of the required functionality has already been implemented there.

**Comment by wemu** [comment]
does the new endpoint support both the properties and relations?

**Comment by RetGal** [comment]
Yes, it returns complete ReleaseDTOs, containing Relations, Properties, ResourceTags and Templates. Same format/content as  `GET /resources/{resourceGroupName}/{releaseName}`

**Comment by wemu** [comment]
the /lte/ resource does not yet seem to work. for example:

server: "ovn" which has release RL-17.04:
**/AMW_rest/resources/./resources/ovn/lte/RL-17.04** does return a result

but **/AMW_rest/resources/./resources/ovn/lte/RL-17.10** returns a 404 - but I would have expected it to fallback to RL-17.04 (the newer release exists and comes after 17.04, verified in the deployment dialog)

**Comment by RetGal** [comment]
Thanks for the feedback, it's fixed now.
