### ISSUE TITLE
Create Resource Type Template creates a relation template instead of Resource Type Template

### ISSUE THREAD

**Issue by phil-pona** [liimaorg/liima#92]
Fall 1
Die URL nach dem Klick auf **New Template** auf dem ResourceType Edit Screen ist https://Server/AMW_web/pages/editTemplateView.xhtml?resTypId=2&rel=2851&lnWrap=false
Lege ich ein neues Template an, erscheint es unten als Relationship Template.

Fall 2 
URL https://Server/AMW_web/pages/editTemplateView.xhtml?resTypId=2&rel=2851&lnWrap=false so anpassen, dass der rel param fehlt:
https://Server/AMW_web/pages/editTemplateView.xhtml?resTypId=2&lnWrap=false wird dann das neue Template korrekt angelegt.

**Comment by RetGal** [comment]
Mit welcher Wildfly/EAP Version tritt dieses Problem auf? Ich kann das beschriebene Verhalten mit EAP 6.4 nicht reproduzieren.

**Comment by RetGal** [comment]
Konnte das Fehlverhalten mit 1.12.2 unabhängig vom Datenbestand reproduzieren. Mit 1.12.3 tritt dieses Problem nicht mehr auf.
