### ISSUE TITLE
resourceList.xhtml slow with lots of resource instances 

### ISSUE THREAD

**Issue by yvespp** [liimaorg/liima#96]
**Release**: v1.13.0-beta.1

Openen the list of resources on resourceList.xhtml takes a lot longer in 1.13 than it did in Liima 1.12:
* Selecting `APPLICATIONS` take on our Liima test environment 21 seconds, in prod with 1.12 it takes 1.5 seconds. There are about 600 apps.
* Selecting `Webservice` with about 440 resources takes also 21 seconds to load, in prod with 1.12 it takes 0.9 seconds.
* Resource list with less instances load a lot quicker.

**Comment by yvespp** [comment]
Clicking the `Add shakedown test` on the shakedownTest screen is also very slow (17.5 s). Probably also because listing the app servers is slow.

**Comment by RetGal** [comment]
- resourceList selecting `APPLICATION` dropped from ~25s to ~4s
- resourceList selecting `Webservice` dropped from ~12s to <3s
- `Add shakedown test` dropped from ~13s to <1.5s
(on my machine, measured in Chrome)
